In [1]:
import torch
import mindspore as ms
from mindspore import Tensor

In [242]:
m = torch.randn(5, 4, 3)

In [244]:
mm = torch.nn.Softmax(dim=-1)(m)

In [251]:
mm.sum(-1).all() == 1

tensor(True)

In [2]:
from mindspore.nn import Dropout, LayerNorm
from mindspore import ops as P
import mindspore.numpy

In [254]:
n = mindspore.numpy.randn(5, 4, 3)
nn = mindspore.nn.Softmax(axis=-1)(n)

In [300]:
import numpy

In [168]:
import torch
def ForLoop_L2_weight_torch(x:torch.Tensor, dim):
    a = x.clone()
    slices = [slice(None) for i in range(x.ndim)]
    sum1 = 0
    for i in range(x.shape[dim]):
        slices[dim] = i
        idx_slice = tuple(slices)
        # print(idx_slice)
        sum1 += x[idx_slice] ** 2

    sum2 = 0
    for i in range(x.shape[dim]):
        slices[dim] = i
        idx_slice = tuple(slices)
        if i != x.shape[dim] - 1:
            a[idx_slice] = x[idx_slice] ** 2 / sum1
            sum2 += a[idx_slice]
        else:
            a[idx_slice] = 1 - sum2

    return a

In [169]:
from mindspore import Tensor
def ForLoop_L2_weight_ms(x:Tensor, dim):
    a = x.copy()
    slices = [slice(None) for i in range(x.ndim)]
    sum1 = 0
    for i in range(x.shape[dim]):
        slices[dim] = i
        idx_slice = tuple(slices)
        # print(idx_slice)
        sum1 += x[idx_slice] ** 2

    sum2 = 0
    for i in range(x.shape[dim]):
        slices[dim] = i
        idx_slice = tuple(slices)
        if i != x.shape[dim] - 1:
            a[idx_slice] = x[idx_slice] ** 2 / sum1
            sum2 += a[idx_slice]
        else:
            a[idx_slice] = 1 - sum2

    return a

In [170]:
from mindspore import numpy as np
x = np.randn(10, 20, 755)

In [171]:
y = torch.from_numpy(x.asnumpy())

In [172]:
yy = ForLoop_L2_weight_torch(y, -1)

In [173]:
xx = ForLoop_L2_weight_ms(x, -1)

In [183]:
(xx.asnumpy() == yy.detach().numpy()).all()

True

In [379]:
x = numpy.random.randn(4, 5, 5)
dim = -1
a = ForLoop_L2_weight(x, dim)
print(a.sum(dim))

(slice(None, None, None), slice(None, None, None), 0)
(slice(None, None, None), slice(None, None, None), 1)
(slice(None, None, None), slice(None, None, None), 2)
(slice(None, None, None), slice(None, None, None), 3)
(slice(None, None, None), slice(None, None, None), 4)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [388]:
x1 = ms.numpy.randn(4, 5, 5)
dim = -1
a1 = ForLoop_L2_weight(x1, dim)

(slice(None, None, None), slice(None, None, None), 0)
(slice(None, None, None), slice(None, None, None), 1)
(slice(None, None, None), slice(None, None, None), 2)
(slice(None, None, None), slice(None, None, None), 3)
(slice(None, None, None), slice(None, None, None), 4)


In [389]:
print(a1.sum(-1).asnumpy())

[[1.         1.         1.         0.99999994 1.        ]
 [1.         1.         0.99999994 1.         0.99999994]
 [1.         0.99999994 1.         1.         1.        ]
 [1.         1.         0.99999994 1.         1.        ]]


In [390]:
print(a1.asnumpy().sum(-1))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [334]:
a1.sum(-1).asnumpy() == a.sum(-1)

array([[ True,  True, False,  True, False],
       [ True, False, False,  True, False],
       [False, False,  True,  True, False],
       [ True,  True,  True, False, False]])

In [284]:
print(a.sum(-1))

[[1.71273677 1.87997114 1.89289991 2.10592656 2.00855055]
 [2.05211375 1.89369548 2.08435012 1.75468206 2.08926579]
 [1.98841168 1.86742908 1.82573692 1.6680897  1.93287007]
 [2.18620448 1.74255429 2.02136599 1.8921174  1.77529027]]


In [ ]:
import numpy
def manual_sum(x: numpy.ndarray):
    

In [256]:
nn.sum(-1)

Tensor(shape=[5, 4], dtype=Float32, value=
[[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
 [ 1.00000012e+00,  9.99999940e-01,  1.00000000e+00,  1.00000000e+00],
 [ 1.00000012e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
 [ 1.00000000e+00,  1.00000000e+00,  9.99999940e-01,  1.00000000e+00],
 [ 1.00000000e+00,  9.99999940e-01,  9.99999940e-01,  1.00000000e+00]])

In [27]:
l = mindspore.numpy.randn(10, 5, 3)

In [22]:
a = Dropout(keep_prob=0.0)

In [36]:
(a(l) == l).all()

Tensor(shape=[], dtype=Bool, value= True)

In [37]:
import torch.nn
b = torch.nn.Dropout(p=0.0, inplace=False)

In [38]:
l_2 = torch.from_numpy(l.asnumpy())

In [39]:
(b(l_2) == l_2).all()

tensor(True)

In [98]:
from mindspore import numpy as np
from mindspore import ops as P

In [99]:
x = np.randn(10, 32, 974)

In [101]:
out_channels = 3560
in_channels = x.shape[-1]
multi = int(out_channels / in_channels)
rem = int(out_channels % in_channels)
rep_tuple = [1] * x.ndim
rep_tuple[-1] = multi
rep_tuple = tuple(rep_tuple)
y = np.tile(x, rep_tuple)
print((multi, rem), x.shape, y.shape)
P.concat((y, x[..., :rem]), axis=-1).shape

(3, 638) (10, 32, 974) (10, 32, 2922)


(10, 32, 3560)

In [133]:
attention_probs_dropped_path = "/mnt/d/compare/attention_probs.pth"
value_layer_path = "/mnt/d/compare/value_layer.pth"

In [134]:
attention_probs_dropped = torch.load(attention_probs_dropped_path)
value_layer = torch.load(value_layer_path)

In [135]:
context_layer_pytorch = torch.matmul(attention_probs_dropped, value_layer)

In [136]:
context_layer_pytorch.shape

torch.Size([100, 12, 32, 64])

In [137]:
attention_probs_dropped_ms = Tensor.from_numpy(attention_probs_dropped.detach().numpy())
value_layer_ms = Tensor.from_numpy(value_layer.detach().numpy())

In [138]:
context_layer_ms = P.matmul(attention_probs_dropped_ms, value_layer_ms)

In [139]:
np.abs(context_layer_ms.asnumpy() - context_layer_pytorch.detach().numpy()).max()

0.0

In [261]:
# param_name = "fixed_attention_probs"
param_name = "outside_hidden_states"
# param_name = "past_key_value"

In [262]:
torch_dict = "/mnt/d/compare/" + param_name + ".pth"
tt = torch.load(torch_dict)

In [263]:
ms_dict = "/mnt/d/compare/" + param_name + ".ckpt"
mm = ms.load_checkpoint(ms_dict)
mm = mm[param_name].value()

In [264]:
# import numpy.linalg as npl
import numpy as np
np.abs(mm.asnumpy() - tt.detach().numpy()).max()

0.0

In [ ]:
4

In [2]:
import numpy
def compare_ms_torch_for_param(param_name: str):
    torch_dict = "/mnt/d/compare/" + param_name + ".pth"
    tt = torch.load(torch_dict)
    ms_dict = "/mnt/d/compare/" + param_name + ".ckpt"
    mm = ms.load_checkpoint(ms_dict)
    mm = mm[param_name].value()
    return numpy.abs(mm.asnumpy() - tt.detach().numpy()).max()

In [262]:
# param_names = ['context_layer','outputs[1][0]', 'outputs[1][1]']
# num - 11
# param_names = ["hidden_states", "attention_mask", "encoder_hidden_states", "encoder_attention_mask", "layer_outputs[1][0]", "layer_outputs[1][1]"]
# param_names = ["hidden_states", "attention_mask", "encoder_hidden_states", "encoder_attention_mask", "attention_output"]
param_names = ["hidden_states", "attention_mask", "attention_output"]
for param_name in param_names:
    print("{}: {}".format(param_name, compare_ms_torch_for_param(param_name)))

hidden_states: 0.0
attention_mask: 0.0
attention_output: 3.814697265625e-06


In [ ]:
save_params({"hidden_states":hidden_states, "attention_mask":attention_mask, "encoder_hidden_states":encoder_hidden_states, "encoder_attention_mask":encoder_attention_mask, "layer_outputs[1][0]":layer_outputs[1][0], "layer_outputs[1][1]":layer_outputs[1][1]})

In [9]:
query_output_num = 25
param_names = ["query_output_{}".format(i) for i in range(query_output_num)]
for param_name in param_names:
    print("{}: {}".format(param_name, compare_ms_torch_for_param(param_name)))

query_output_0: 3.814697265625e-06
query_output_1: 0.0
query_output_2: 0.0
query_output_3: 0.0
query_output_4: 0.0
query_output_5: 0.0
query_output_6: 0.0
query_output_7: 0.0
query_output_8: 0.0
query_output_9: 0.0
query_output_10: 0.0
query_output_11: 0.0
query_output_12: 0.0
query_output_13: 0.0
query_output_14: 0.0
query_output_15: 0.0
query_output_16: 0.0
query_output_17: 0.0
query_output_18: 0.0
query_output_19: 0.0
query_output_20: 0.0
query_output_21: 0.0
query_output_22: 0.0
query_output_23: 1.9073486328125e-06
query_output_24: 1.9073486328125e-06


In [10]:
text_output_num = 1
param_names = ["text_output_{}".format(i) for i in range(text_output_num)]
for param_name in param_names:
    print("{}: {}".format(param_name, compare_ms_torch_for_param(param_name)))

text_output_0: 9.685754776000977e-08


In [11]:
output_itm_num = 1
param_names = ["output_itm_{}".format(i) for i in range(output_itm_num)]
for param_name in param_names:
    print("{}: {}".format(param_name, compare_ms_torch_for_param(param_name)))

output_itm_0: 0.0


In [ ]:
save_params({"context_layer":context_layer, "outputs[1][0]":outputs[1][0], "outputs[1][1]":outputs[1][1]})

In [81]:
def save_params(params:dict):
    for name, params in params.items():
        save_param(param, name)

In [54]:
# tt.detach().numpy()

In [55]:
# mm[param_name].value().asnumpy()

# Diffs: 

### nn.LayerNorm | nn.SoftMax(dim = -1)  | torch.mean/P.Reduced_mean | torch.sum | P.Reduced_sum

## *LayerNorm*

In [15]:
param_name_2 = "LayerNorm"

torch_dict = "/mnt/d/compare/" + param_name_2 + ".pth"
ln = torch.load(torch_dict)

ms_dict = "/mnt/d/compare/" + param_name_2 + ".ckpt"
ln2_dict = ms.load_checkpoint(ms_dict)

In [16]:
from mindspore.nn import LayerNorm
ln2 = LayerNorm((768,), epsilon=1e-12)
ms.load_param_into_net(ln2, ln2_dict)

[WARNING] ME(793:139782206034304,MainProcess):2023-06-15-10:00:40.368.554 [mindspore/train/serialization.py:736] For 'load_param_into_net', remove parameter prefix name: bert.embeddings.LayerNorm., continue to load.


[]

In [17]:
ln.elementwise_affine=False

In [18]:
ln

LayerNorm((768,), eps=1e-12, elementwise_affine=False)

In [19]:
ln2

LayerNorm<normalized_shape=(768,), begin_norm_axis=-1, begin_params_axis=-1, gammaParameter (name=gamma, shape=(768,), dtype=Float32, requires_grad=True), beta=Parameter (name=beta, shape=(768,), dtype=Float32, requires_grad=True)>

In [20]:
(ln.bias.detach().numpy() == ln2.beta.value().asnumpy()).all()

True

In [21]:
(ln.weight.detach().numpy() == ln2.gamma.value().asnumpy()).all()

True

In [22]:
ln.eps == ln2.epsilon

True

In [23]:
(mm.asnumpy() == tt.detach().numpy()).all()

True

In [24]:
np.abs(ln2(mm).asnumpy() - ln(tt).detach().numpy()).max()

0.0011546612

## *Linear*

In [25]:
param_name_2 = "Dense"

torch_dict = "/mnt/d/compare/" + param_name_2 + ".pth"
ln = torch.load(torch_dict)

ms_dict = "/mnt/d/compare/" + param_name_2 + ".ckpt"
ln2_dict = ms.load_checkpoint(ms_dict)

In [26]:
ln

Linear(in_features=768, out_features=768, bias=True)

In [27]:
from mindspore.nn import Dense
ln2 = Dense(ln.in_features, ln.out_features)
ms.load_param_into_net(ln2, ln2_dict)

[WARNING] ME(793:139782206034304,MainProcess):2023-06-15-10:00:46.974.358 [mindspore/train/serialization.py:736] For 'load_param_into_net', remove parameter prefix name: bert.encoder.layer.0.attention.output.dense., continue to load.


[]

In [28]:
ln2

Dense<input_channels=768, output_channels=768, has_bias=True>

In [29]:
(ln.weight.detach().numpy() == ln2.weight.value().asnumpy()).all()

True

In [30]:
(ln.bias.detach().numpy() == ln2.bias.value().asnumpy()).all()

True

In [31]:
tt = torch.randn(10, 2, ln.in_features)

In [32]:
mm = Tensor.from_numpy(tt.detach().numpy())

In [33]:
np.abs(ln2(mm).asnumpy() - ln(tt).detach().numpy()).max()

4.7683716e-07